/* How to Schweiz – alle Texte (DE / EN / Schwiizerdütsch)
 * Platzhalter in eckigen Klammern vor dem Livegang ersetzen. */

// Leistungen: interne ID → URL-Name der Unterseite
exports.services = [
  { id: 'svc1', slug: 'grenzgaenger-auswanderung' },
  { id: 'svc2', slug: 'krankenversicherung' },
  { id: 'svc3', slug: 'altersvorsorge' },
  { id: 'svc4', slug: 'steuern' },
  { id: 'svc5', slug: 'bank-saeule-3a' },
  { id: 'svc6', slug: 'absicherung' }
];

exports.de = {
  html_lang: 'de', og_locale: 'de_DE', lang_name: 'Deutsch',
  meta_title: 'How to Schweiz – Ihr Weg nach Basel und in die Schweiz',
  meta_description: 'Auswandern in die Schweiz: persönliche Begleitung bei Krankenkasse, Vorsorge, Säule 3a, Steuern und Bankkonto – von jemandem, der den Weg von Deutschland nach Basel selbst gegangen ist.',
  skip: 'Zum Inhalt springen', menu: 'Menü', lang_label: 'Sprache',
  nav_leistungen: 'Leistungen', nav_ablauf: 'Ablauf', nav_ueberuns: 'Über uns', nav_faq: 'FAQ', nav_kontakt: 'Kontakt', nav_cta: 'Erstgespräch sichern',
  hero_eyebrow: 'Von Deutschland nach Basel',
  hero_title: 'Ihr Weg in die Schweiz — klar geplant, sicher begleitet.',
  hero_text: 'Sami Kaune und sein Team begleiten Sie beim Wechsel nach Basel und in die Schweiz — bei Vorsorge, Versicherung, Steuern und allem, was beim Auswandern wirklich zählt. Persönlich begleitet, mit Blick für beide Seiten der Grenze.',
  hero_cta1: 'Kostenloses Erstgespräch', hero_cta2: 'Leistungen ansehen',
  usp1_title: 'Beide Seiten der Grenze', usp1_text: 'Sami und sein Team behalten beide Rechts- und Vorsorgesysteme im Blick — auf deutscher wie auf Schweizer Seite.',
  usp2_title: 'Persönlich begleitet', usp2_text: 'Vom ersten Gespräch bis zur Anmeldung in der Schweiz — ein fester Ansprechpartner, kein Callcenter.',
  usp3_title: 'Ganzheitlich gedacht', usp3_text: 'Vorsorge, Versicherung, Steuern und Banking — koordiniert aus einer Hand statt in Einzelteilen.',
  stats_eyebrow: 'Die Schweiz in Zahlen', stats_title: 'Was Sie in der Schweiz erwartet.',
  stat1_value: "CHF 7'024", stat1_label: 'Medianlohn pro Monat, brutto, Vollzeit (2024)',
  stat2_value: 'CHF 694', stat2_label: 'Standardprämie Krankenkasse in Basel-Stadt pro Monat (Erwachsene, Franchise 300, 2026)',
  stat3_value: '27,7 %', stat3_label: 'der Bevölkerung ohne Schweizer Pass (2025) — Sie sind nicht allein',
  stats_source: 'Quellen: Bundesamt für Statistik (Lohnstrukturerhebung 2024, Bevölkerungsstatistik 2025), Gesundheitsdepartement Basel-Stadt / BAG (Prämien 2026)',
  about_eyebrow: 'Über uns', about_title: 'Von jemandem, der den Weg selbst gegangen ist.',
  about_text: 'How to Schweiz setzt genau dort an, wo klassische Beratung oft aufhört: an der Grenze. Wir begleiten Menschen, die beruflich oder privat den Schritt in die Schweiz wagen — mit Blick für das deutsche und das Schweizer System und einem Netzwerk aus Spezialisten, wenn es konkret wird.',
  sami_role: 'Ihr Ansprechpartner in Basel',
  sami_text: 'Sami hat den Wechsel selbst durchlebt: Er ist aus Deutschland in die Schweiz ausgewandert und kennt die Hürden nicht aus der Theorie, sondern aus eigener Erfahrung. Vor Ort in Basel zu Hause und Ihre Anlaufstelle für die Schweizer Seite: Krankenversicherung, Pensionskasse und die praktischen Fragen rund um den Neustart.',
  network_eyebrow: 'Unser Netzwerk', network_title: 'Starke Partner in der Schweiz.',
  network_text: 'Für alles, was über Vorsorge und Versicherung hinausgeht, arbeiten wir mit einem eingespielten Netzwerk in der Schweiz zusammen — darunter Rechtsanwälte für aufenthalts- und arbeitsrechtliche Fragen, Steuerberater für die steuerliche Seite Ihres Umzugs sowie weitere Spezialisten je nach Bedarf. So finden Sie schnell die richtige Ansprechperson, ohne selbst suchen zu müssen.',
  network_item1: 'Rechtsanwälte', network_item2: 'Steuerberater', network_item3: 'Weitere Spezialisten',
  leistungen_eyebrow: 'Leistungen', leistungen_title: 'Alles, was beim Wechsel zählt.',
  more_label: 'Mehr erfahren →', back_label: '← Zurück zur Übersicht', home_label: '← Zurück zur Startseite',
  svc1_title: 'Grenzgänger- & Auswanderungsberatung', svc1_text: 'Eine ehrliche Standortbestimmung: Wie Sozialsystem, Krankenkasse und die drei Säulen der Vorsorge zusammenspielen — und was das konkret für Sie bedeutet.',
  svc2_title: 'Krankenversicherung Schweiz', svc2_text: "Anders als in Deutschland wählen Sie Ihre Krankenkasse selbst, unabhängig vom Arbeitgeber — Pflicht innerhalb von drei Monaten. Wir begleiten Sie bei Grundversicherung, Franchise (CHF 300–2'500) und Zusatzversicherungen.",
  svc3_title: 'Altersvorsorge & Rentenübertragung', svc3_text: 'Einordnung von AHV, Pensionskasse (BVG) — bei der Ihr Arbeitgeber mindestens die Hälfte einzahlt — und Säule 3a, inklusive Einkaufsmöglichkeiten und was mit bestehenden deutschen Ansprüchen passiert.',
  svc4_title: 'Steuerliche Fragen', svc4_text: 'Orientierung zu Quellensteuer, Doppelbesteuerungsabkommen und Ihrer steuerlichen Ansässigkeit nach dem Umzug.',
  svc5_title: 'Bankverbindung & Vorsorgeprodukte', svc5_text: 'Unterstützung beim Bankkonto sowie bei der Säule 3a — steuerlich absetzbar und für Deutsche besonders attraktiv, da es dort keine vergleichbare Förderung gibt. Anlage auch in Fonds oder ETFs möglich.',
  svc6_title: 'Absicherung für den Neustart', svc6_text: 'Die Pensionskasse sichert bereits bei Invalidität und im Todesfall ab — wir prüfen, ob das für Sie reicht oder ergänzt werden sollte.',
  ablauf_eyebrow: 'Ablauf', ablauf_title: 'So läuft die Zusammenarbeit.',
  step1_title: 'Kennenlernen', step1_text: 'Unverbindliches Erstgespräch: Wir hören uns Ihre Situation und Ihre Pläne in Ruhe an.',
  step2_title: 'Analyse', step2_text: 'Wir prüfen Ihre aktuelle Vorsorge-, Versicherungs- und Steuersituation auf beiden Seiten der Grenze.',
  step3_title: 'Konzept', step3_text: 'Sie erhalten ein individuelles Konzept für Ihren Wechsel — klar und nachvollziehbar erklärt.',
  step4_title: 'Umsetzung & Begleitung', step4_text: 'Wir setzen die Maßnahmen gemeinsam um und bleiben auch nach dem Umzug Ihr Ansprechpartner.',
  faq_eyebrow: 'Häufige Fragen', faq_title: 'Was Auswanderer uns am häufigsten fragen.',
  faq_note: 'Stand: 2026. Die Antworten geben einen ersten Überblick und ersetzen keine individuelle Beratung.',
  faq: [
    { q: 'Welche Bewilligung brauche ich als Deutsche oder Deutscher?',
      a: 'Dank dem Freizügigkeitsabkommen zwischen der EU und der Schweiz ist der Weg vergleichsweise einfach. Mit einem Arbeitsvertrag ab einem Jahr oder unbefristet erhalten Sie in der Regel die Aufenthaltsbewilligung B, bei kürzeren Verträgen die Kurzaufenthaltsbewilligung L. Wer in Deutschland wohnen bleibt und mindestens einmal pro Woche dorthin zurückkehrt, bekommt die Grenzgängerbewilligung G. Nach dem Umzug melden Sie sich innerhalb von 14 Tagen und vor Arbeitsbeginn bei Ihrer Wohngemeinde an.' },
    { q: 'Bis wann muss ich mich krankenversichern?',
      a: 'Innerhalb von drei Monaten nach dem Zuzug. Die Versicherung gilt dann rückwirkend ab dem Tag Ihres Zuzugs. Grenzgänger aus Deutschland haben ein Wahlrecht: Sie können sich innerhalb von drei Monaten nach Arbeitsbeginn für die Schweizer Krankenversicherung oder für eine Versicherung in Deutschland entscheiden. Diese Wahl lässt sich später nur in Ausnahmefällen ändern.' },
    { q: 'Was kostet die Krankenkasse in Basel?',
      a: "Die Standardprämie für Erwachsene in Basel-Stadt liegt 2026 bei CHF 694 pro Monat (Franchise CHF 300, mit Unfalldeckung). Mit einer höheren Franchise oder einem Hausarzt- bzw. Telmed-Modell zahlen Sie spürbar weniger. Wer mindestens 8 Stunden pro Woche angestellt ist, ist über den Arbeitgeber gegen Unfall versichert und kann die Unfalldeckung in der Krankenkasse ausschließen." },
    { q: 'Was passiert mit meiner deutschen Rente?',
      a: 'Ihre in Deutschland erworbenen Ansprüche bleiben erhalten. Beitragszeiten in beiden Ländern werden für die Mindestversicherungszeiten gegenseitig angerechnet. Im Rentenalter zahlt jedes Land den Teil, den Sie dort erworben haben — die deutsche Rente kann auch in die Schweiz überwiesen werden.' },
    { q: 'Wie werde ich in der Schweiz besteuert?',
      a: "Mit einer B-Bewilligung wird die Steuer zunächst direkt vom Lohn abgezogen (Quellensteuer). Liegt Ihr Bruttolohn über CHF 120'000 pro Jahr, folgt automatisch eine ordentliche Steuererklärung. Darunter können Sie diese bis zum 31. März des Folgejahres beantragen, um zum Beispiel Einzahlungen in die Säule 3a abzuziehen. Grenzgänger zahlen in der Schweiz höchstens 4,5 % Quellensteuer und werden in Deutschland besteuert, wobei die Schweizer Steuer angerechnet wird." },
    { q: 'Wie viel kann ich in die Säule 3a einzahlen?',
      a: "Angestellte mit Pensionskasse können 2026 bis zu CHF 7'258 einzahlen. Ohne Pensionskasse sind es bis zu 20 % des Erwerbseinkommens, höchstens CHF 36'288. Die Einzahlungen können Sie vom steuerbaren Einkommen abziehen." },
    { q: 'Was kostet das Erstgespräch?',
      a: 'Nichts. Das Erstgespräch ist kostenlos und unverbindlich. Wir hören uns Ihre Situation an und sagen Ihnen offen, wo wir helfen können.' }
  ],
  kontakt_eyebrow: 'Kontakt', kontakt_title: 'Bereit für Ihren Neustart?',
  kontakt_text: 'Schreiben Sie uns kurz Ihre Situation — wir melden uns für ein unverbindliches Erstgespräch bei Ihnen.',
  label_name: 'Name', label_email: 'E-Mail', label_phone: 'Telefon (optional)', label_situation: 'Ihre Situation',
  label_consent_before: 'Ich bin einverstanden, dass meine Angaben zur Bearbeitung meiner Anfrage verwendet werden. Mehr dazu in der ', label_consent_link: 'Datenschutzerklärung', label_consent_after: '.',
  btn_send: 'Nachricht senden',
  form_invalid: 'Bitte füllen Sie Name, E-Mail und Ihre Situation aus und bestätigen Sie die Einwilligung.',
  form_nomail: 'Das Kontaktformular ist noch nicht verbunden. Bitte nutzen Sie vorerst die Kontaktdaten.',
  form_ok: 'Ihr E-Mail-Programm wird geöffnet …', form_subject: 'Anfrage über How to Schweiz',
  sami_contact_role: 'Ansprechpartner Basel, Schweiz',
  ph_phone: '[Telefonnummer]', ph_email: '[E-Mail-Adresse]',
  footer_impressum: 'Impressum', footer_datenschutz: 'Datenschutz', footer_partner: 'Für Berater',
  footer_copyright: '© 2026 How to Schweiz.',
  footer_disclaimer: 'Diese Seite ersetzt keine individuelle Rechts- oder Steuerberatung.',
  details: {
    svc1: { intro: 'Der Wechsel in die Schweiz betrifft mehr als nur den Wohnort: Sozialversicherung, Steuern, Krankenversicherung und Vorsorge folgen eigenen Regeln, die sich in wichtigen Punkten von den deutschen unterscheiden. Eine frühzeitige Standortbestimmung hilft, teure Fehler zu vermeiden.',
      h1: 'Grenzgänger oder Auswanderer?', p1: 'Ob Sie in der Schweiz arbeiten und in Deutschland wohnen bleiben (Grenzgänger) oder ganz umziehen, macht einen erheblichen Unterschied — bei Steuern, Sozialversicherung und Krankenkasse gelten jeweils andere Regeln. Wir klären zu Beginn, welche Situation auf Sie zutrifft.',
      h2: 'Die wichtigsten Baustellen im Überblick', p2: 'Krankenversicherung (Pflicht innerhalb von drei Monaten), die drei Säulen der Altersvorsorge, die steuerliche Ansässigkeit sowie mögliche Doppelbesteuerung — all das hängt zusammen und sollte nicht isoliert betrachtet werden. Genau hier setzt unsere Beratung an.',
      h3: 'Der Wohnort entscheidet mit', p3: 'Die Schweiz hat 26 Kantone mit jeweils eigener Steuerhoheit, und auch innerhalb eines Kantons setzt jede Gemeinde ihren eigenen Steuerfuß. Dadurch können schon wenige Kilometer — manchmal sogar eine Straße weiter in der Nachbargemeinde oder im Nachbarkanton — einen spürbaren Unterschied bei der Steuerlast machen. Wir denken diese Frage frühzeitig mit, bevor Sie sich für einen Wohnort entscheiden.' },
    svc2: { intro: 'Innerhalb von drei Monaten nach dem Zuzug müssen Sie sich bei einer Schweizer Krankenkasse versichern — anders als in Deutschland wählen Sie diese komplett frei, unabhängig von einem Arbeitgeber.',
      h1: 'Grundversicherung (KVG): gesetzlich gleich, im Service unterschiedlich', p1: "Die Leistungen der obligatorischen Grundversicherung sind bei jeder Krankenkasse identisch — Ärzte, Spitalaufenthalte und Medikamente sind abgedeckt. Unterschiede zeigen sich vor allem bei Prämie, Service und der Wahl der Franchise, die zwischen CHF 300 und CHF 2'500 pro Jahr liegt: Je höher die Franchise, desto tiefer die monatliche Prämie.",
      h2: 'Zusatzversicherung: sinnvoll ergänzen', p2: 'Freiwillige Zusatzversicherungen decken zum Beispiel halbprivate oder private Spitalabteilung, Chefarztbehandlung, alternative Heilmethoden oder Beiträge an Fitness-Abos ab. Wir schauen gemeinsam, was für Ihre Situation sinnvoll ist — und was nicht.' },
    svc3: { intro: 'Die Schweizer Altersvorsorge ruht auf drei Säulen, die zusammen den Lebensstandard im Alter sowie bei Invalidität und im Todesfall sichern sollen.',
      h1: 'Die drei Säulen', p1: '1. Säule (AHV): die staatliche Grundabsicherung, obligatorisch für alle. 2. Säule (Pensionskasse/BVG): die berufliche Vorsorge über den Arbeitgeber, der mindestens die Hälfte der Beiträge übernimmt. 3. Säule: die freiwillige, private Ergänzung — die Säule 3a ist dabei steuerlich absetzbar und in Deutschland ohne direkte Entsprechung.',
      h2: 'Was mit deutschen Ansprüchen passiert', p2: 'Bestehende deutsche Rentenansprüche gehen beim Wechsel nicht verloren, folgen aber eigenen Regeln — das Freizügigkeitsabkommen zwischen der EU und der Schweiz koordiniert beide Systeme. Bei einem Wechsel der Pensionskasse lohnt sich zudem ein Blick auf Deckungsgrad und mögliche Einkaufsmöglichkeiten. Die genauen Auswirkungen besprechen wir anhand Ihrer persönlichen Situation.' },
    svc4: { intro: 'Mit dem Wechsel in die Schweiz ändert sich auch Ihre steuerliche Situation — insbesondere im Umzugsjahr lohnt sich ein genauer Blick, um Doppelbesteuerung zu vermeiden.',
      h1: 'Quellensteuer und Doppelbesteuerungsabkommen', p1: 'Viele Zugezogene werden in der Schweiz zunächst direkt an der Quelle besteuert. Das Doppelbesteuerungsabkommen zwischen Deutschland und der Schweiz regelt, welchem Land in welchen Fällen das Besteuerungsrecht zusteht, damit Einkommen nicht doppelt versteuert wird.',
      h2: 'Steuerliche Ansässigkeit', p2: 'Wo Sie steuerlich ansässig sind, hängt von Wohnsitz und Lebensmittelpunkt ab — gerade im Übergangsjahr ist das nicht immer eindeutig. Wir ordnen Ihre individuelle Situation ein und verweisen bei Bedarf an spezialisierte Steuerberatung.' },
    svc5: { intro: 'Ein Schweizer Bankkonto und die richtige Vorsorgelösung gehören zu den ersten praktischen Schritten nach dem Zuzug.',
      h1: 'Säule 3a: steuerlich absetzbar', p1: "Einzahlungen in die Säule 3a können vom steuerbaren Einkommen abgezogen werden — 2026 bis zu CHF 7'258 für Angestellte mit Pensionskasse. Einen solchen Vorteil gibt es in dieser Form in Deutschland nicht. Je nach Lösung wird das Kapital verzinst oder in Fonds beziehungsweise ETFs investiert, um langfristig Vermögen aufzubauen.",
      h2: 'Bankkonto und bestehende Verträge', p2: 'Wir unterstützen bei der Kontoeröffnung und schauen uns an, welche bestehenden deutschen Verträge — etwa Lebensversicherungen oder Sparpläne — sinnvoll weitergeführt oder angepasst werden sollten.' },
    svc6: { intro: 'Ein Neustart in der Schweiz ist auch ein guter Zeitpunkt, die eigene Absicherung zu überprüfen.',
      h1: 'Was die Pensionskasse bereits abdeckt', p1: 'Die 2. Säule schützt nicht nur im Alter, sondern auch bei Invalidität und im Todesfall — bei Erwerbsunfähigkeit oder für Hinterbliebene können Leistungen ausbezahlt werden. Wie hoch diese ausfallen, hängt vom jeweiligen Vorsorgeplan ab.',
      h2: 'Wo sich eine Ergänzung lohnen kann', p2: 'Ob die eingebaute Absicherung für Ihre Familiensituation ausreicht oder eine private Ergänzung sinnvoll ist, prüfen wir gemeinsam — genauso wie die Frage, ob bestehende deutsche Policen nach dem Umzug noch passen.' }
  }
};

exports.en = {
  html_lang: 'en', og_locale: 'en_GB', lang_name: 'English',
  meta_title: 'How to Schweiz – Your move to Basel and Switzerland',
  meta_description: 'Moving to Switzerland: personal guidance on health insurance, pensions, pillar 3a, taxes and banking – from someone who made the move from Germany to Basel himself.',
  skip: 'Skip to content', menu: 'Menu', lang_label: 'Language',
  nav_leistungen: 'Services', nav_ablauf: 'Process', nav_ueberuns: 'About us', nav_faq: 'FAQ', nav_kontakt: 'Contact', nav_cta: 'Book a free call',
  hero_eyebrow: 'From Germany to Basel',
  hero_title: 'Your path to Switzerland — clearly planned, safely guided.',
  hero_text: 'Sami Kaune and his team support you with the move to Basel and Switzerland — with pension planning, insurance, taxes and everything that really matters when emigrating. Personally guided, with an eye on both sides of the border.',
  hero_cta1: 'Free initial consultation', hero_cta2: 'View services',
  usp1_title: 'Both sides of the border', usp1_text: 'Sami and his team keep both legal and pension systems in view — on the German side as much as the Swiss.',
  usp2_title: 'Personally guided', usp2_text: 'From the first conversation to registering in Switzerland — one dedicated contact, not a call centre.',
  usp3_title: 'Thought through, holistically', usp3_text: 'Pension planning, insurance, taxes and banking — coordinated in one place instead of piecemeal.',
  stats_eyebrow: 'Switzerland in numbers', stats_title: 'What to expect in Switzerland.',
  stat1_value: 'CHF 7,024', stat1_label: 'Median gross monthly salary, full-time (2024)',
  stat2_value: 'CHF 694', stat2_label: 'Standard monthly health insurance premium in Basel-Stadt (adults, CHF 300 deductible, 2026)',
  stat3_value: '27.7%', stat3_label: 'of the population holds no Swiss passport (2025) — you won\'t be alone',
  stats_source: 'Sources: Swiss Federal Statistical Office (Swiss Earnings Structure Survey 2024, population statistics 2025), Basel-Stadt Health Department / FOPH (premiums 2026)',
  about_eyebrow: 'About us', about_title: 'From someone who has made the move himself.',
  about_text: 'How to Schweiz starts exactly where classic advice often stops: at the border. We support people taking the step to Switzerland, professionally or privately — with an eye on both the German and the Swiss system, and a network of specialists when things get specific.',
  sami_role: 'Your contact in Basel',
  sami_text: 'Sami has lived through the move himself — he emigrated from Germany to Switzerland and knows the hurdles not from theory, but from his own experience. At home in Basel and your point of contact for the Swiss side: health insurance, pension fund and the practical questions around your fresh start.',
  network_eyebrow: 'Our network', network_title: 'Strong partners in Switzerland.',
  network_text: 'For anything beyond pension planning and insurance, we work with an established network in Switzerland — including lawyers for residence and employment law questions, tax advisors for the tax side of your move, and other specialists as needed. That way you quickly find the right contact, without having to search yourself.',
  network_item1: 'Lawyers', network_item2: 'Tax advisors', network_item3: 'Other specialists',
  leistungen_eyebrow: 'Services', leistungen_title: 'Everything that matters for the move.',
  more_label: 'Learn more →', back_label: '← Back to overview', home_label: '← Back to home page',
  svc1_title: 'Cross-border & emigration advice', svc1_text: 'An honest starting point: how the social system, health insurance and the three pension pillars work together — and what that means for you specifically.',
  svc2_title: 'Swiss health insurance', svc2_text: 'Unlike in Germany, you choose your own health insurer, independent of your employer — mandatory within three months. We guide you through basic insurance, deductible (CHF 300–2,500) and supplementary cover.',
  svc3_title: 'Retirement planning & pension transfer', svc3_text: 'Making sense of AHV, pension fund (BVG) — where your employer pays at least half — and pillar 3a, including voluntary buy-in options and what happens to your existing German pension entitlements.',
  svc4_title: 'Tax questions', svc4_text: 'Guidance on withholding tax, the double taxation agreement and your tax residency after the move.',
  svc5_title: 'Banking & pension products', svc5_text: 'Support with your bank account and pillar 3a — tax-deductible and especially attractive for Germans, since there is no comparable scheme back home. Can also be invested in funds or ETFs.',
  svc6_title: 'Cover for your fresh start', svc6_text: 'The pension fund already covers disability and death — we check whether that\'s enough for you or should be topped up.',
  ablauf_eyebrow: 'Process', ablauf_title: 'How our collaboration works.',
  step1_title: 'Getting to know you', step1_text: 'No-obligation initial conversation: we take the time to listen to your situation and plans.',
  step2_title: 'Analysis', step2_text: 'We review your current pension, insurance and tax situation on both sides of the border.',
  step3_title: 'Concept', step3_text: 'You receive an individual plan for your move — explained clearly and simply.',
  step4_title: 'Implementation & support', step4_text: 'We implement the measures together and remain your point of contact after the move too.',
  faq_eyebrow: 'FAQ', faq_title: 'What people moving to Switzerland ask us most.',
  faq_note: 'As of 2026. These answers give a first overview and do not replace individual advice.',
  faq: [
    { q: 'Which permit do I need as a German citizen?',
      a: 'Thanks to the free movement agreement between the EU and Switzerland, the process is relatively simple. With an employment contract of one year or more, or an open-ended one, you will usually receive residence permit B; shorter contracts lead to short-term permit L. If you keep living in Germany and return there at least once a week, you receive cross-border commuter permit G. After moving, register with your municipality within 14 days and before starting work.' },
    { q: 'When do I have to take out health insurance?',
      a: 'Within three months of arrival. Cover then applies retroactively from the day you moved. Cross-border commuters from Germany have a choice: within three months of starting work, they can opt for Swiss health insurance or for insurance in Germany. This choice can later only be changed in exceptional cases.' },
    { q: 'How much does health insurance cost in Basel?',
      a: 'The standard premium for adults in Basel-Stadt is CHF 694 per month in 2026 (CHF 300 deductible, including accident cover). With a higher deductible or a GP or telemedicine model, you pay noticeably less. If you are employed for at least 8 hours a week, your employer insures you against accidents, so you can exclude accident cover from your health insurance.' },
    { q: 'What happens to my German pension?',
      a: 'Entitlements you have built up in Germany are kept. Contribution periods in both countries count towards each other\'s minimum insurance periods. At retirement, each country pays the part you earned there — and your German pension can be paid into a Swiss account.' },
    { q: 'How will I be taxed in Switzerland?',
      a: 'With a B permit, tax is initially deducted directly from your salary (withholding tax). If your gross salary exceeds CHF 120,000 a year, an ordinary tax return follows automatically. Below that, you can request one by 31 March of the following year, for example to deduct pillar 3a contributions. Cross-border commuters pay at most 4.5% withholding tax in Switzerland and are taxed in Germany, where the Swiss tax is credited.' },
    { q: 'How much can I pay into pillar 3a?',
      a: 'Employees with a pension fund can pay in up to CHF 7,258 in 2026. Without a pension fund, the limit is 20% of earned income, up to CHF 36,288. Contributions are deductible from taxable income.' },
    { q: 'How much does the initial consultation cost?',
      a: 'Nothing. The initial consultation is free and without obligation. We listen to your situation and tell you openly where we can help.' }
  ],
  kontakt_eyebrow: 'Contact', kontakt_title: 'Ready for your fresh start?',
  kontakt_text: 'Send us a short note about your situation — we will get in touch for a no-obligation initial conversation.',
  label_name: 'Name', label_email: 'Email', label_phone: 'Phone (optional)', label_situation: 'Your situation',
  label_consent_before: 'I agree that my details may be used to process my enquiry. More in the ', label_consent_link: 'privacy policy', label_consent_after: ' (German).',
  btn_send: 'Send message',
  form_invalid: 'Please fill in your name, email and situation, and confirm your consent.',
  form_nomail: 'The contact form is not connected yet. Please use the contact details for now.',
  form_ok: 'Opening your email program …', form_subject: 'Enquiry via How to Schweiz',
  sami_contact_role: 'Contact in Basel, Switzerland',
  ph_phone: '[Phone number]', ph_email: '[Email address]',
  footer_impressum: 'Legal notice', footer_datenschutz: 'Privacy policy', footer_partner: 'For advisors',
  footer_copyright: '© 2026 How to Schweiz.',
  footer_disclaimer: 'This page does not replace individual legal or tax advice.',
  details: {
    svc1: { intro: 'Moving to Switzerland involves more than a change of address: social security, taxes, health insurance and pension planning all follow their own rules, which differ from German ones in important ways. An early assessment helps you avoid costly mistakes.',
      h1: 'Cross-border commuter or emigrant?', p1: 'Whether you work in Switzerland while still living in Germany (cross-border commuter) or move entirely makes a substantial difference — different rules apply for taxes, social security and health insurance. We start by clarifying which situation applies to you.',
      h2: 'The main areas at a glance', p2: 'Health insurance (mandatory within three months), the three pension pillars, tax residency and potential double taxation — these all interact and shouldn\'t be looked at in isolation. That\'s exactly where our advice comes in.',
      h3: 'Where you settle matters too', p3: 'Switzerland has 26 cantons, each with its own tax authority, and within a canton every municipality sets its own tax multiplier on top. That means even a few kilometres — sometimes just one street over, in the neighbouring municipality or canton — can make a noticeable difference to your tax bill. We factor this in early, before you settle on where to live.' },
    svc2: { intro: 'Within three months of arrival you must take out health insurance with a Swiss insurer — unlike in Germany, you choose completely freely, independent of any employer.',
      h1: 'Basic insurance (KVG): the same by law, different in service', p1: 'The benefits of mandatory basic insurance are identical at every insurer — doctors, hospital stays and medication are covered. Differences mainly show up in premiums, service and the deductible you choose, which ranges from CHF 300 to CHF 2,500 a year: the higher the deductible, the lower the monthly premium.',
      h2: 'Supplementary insurance: a sensible addition', p2: 'Voluntary supplementary insurance can cover things like semi-private or private hospital wards, treatment by a senior consultant, alternative medicine or contributions to a gym membership. We look together at what makes sense for your situation — and what doesn\'t.' },
    svc3: { intro: 'Swiss retirement provision rests on three pillars that together secure your standard of living in old age, and in the event of disability or death.',
      h1: 'The three pillars', p1: 'Pillar 1 (AHV): the state\'s basic provision, mandatory for everyone. Pillar 2 (pension fund/BVG): occupational provision through your employer, who covers at least half the contributions. Pillar 3: the voluntary private top-up — pillar 3a is tax-deductible and has no direct equivalent in Germany.',
      h2: 'What happens to German entitlements', p2: 'Existing German pension entitlements aren\'t lost when you move, but follow their own rules — the free movement agreement between the EU and Switzerland coordinates both systems. When changing pension funds, it\'s also worth checking the funding ratio and any voluntary buy-in options. We discuss the exact implications based on your personal situation.' },
    svc4: { intro: 'Moving to Switzerland also changes your tax situation — especially in the year of the move, it\'s worth taking a close look to avoid double taxation.',
      h1: 'Withholding tax and the double taxation agreement', p1: 'Many new arrivals are initially taxed at source in Switzerland. The double taxation agreement between Germany and Switzerland governs which country has the right to tax in which cases, so income isn\'t taxed twice.',
      h2: 'Tax residency', p2: 'Where you\'re tax resident depends on your home and the centre of your life — this isn\'t always clear-cut, especially in the transition year. We help place your individual situation and refer you to specialised tax advice where needed.' },
    svc5: { intro: 'A Swiss bank account and the right pension solution are among the first practical steps after moving.',
      h1: 'Pillar 3a: tax-deductible', p1: 'Contributions to pillar 3a can be deducted from taxable income — in 2026 up to CHF 7,258 for employees with a pension fund. There is no comparable advantage in Germany. Depending on the solution, the capital earns interest or is invested in funds or ETFs to build wealth over the long term.',
      h2: 'Bank account and existing contracts', p2: 'We help with opening an account and look at which existing German contracts — such as life insurance or savings plans — should sensibly be continued or adjusted.' },
    svc6: { intro: 'A fresh start in Switzerland is also a good time to review your own cover.',
      h1: 'What the pension fund already covers', p1: 'Pillar 2 protects not only in old age but also in the event of disability and death — benefits can be paid out for incapacity to work or to surviving dependants. How much depends on the specific pension plan.',
      h2: 'Where it can be worth topping up', p2: 'We check together whether the built-in cover is enough for your family situation or whether private cover makes sense — as well as whether existing German policies still fit after the move.' }
  }
};

/* Schwiizerdütsch: durchgehend Sie-Form, Zürcher Schreibweise als neutrale Mitte.
 * Vor dem Livegang von einer Muttersprachlerin / einem Muttersprachler gegenlesen lassen. */
exports.gsw = {
  html_lang: 'gsw', og_locale: 'de_CH', lang_name: 'Schwiizerdütsch',
  meta_title: 'How to Schweiz – Ihre Wäg uf Basel und i d Schwiiz',
  meta_description: 'Uswandere i d Schwiiz: persönlichi Begleitig bi Chrankechasse, Vorsorg, Süüle 3a, Stüüre und Bankkonto – vo öpperem, wo de Wäg vo Dütschland uf Basel sälber gange isch.',
  skip: 'Zum Inhalt springe', menu: 'Menü', lang_label: 'Sprach',
  nav_leistungen: 'Leischtige', nav_ablauf: 'Ablauf', nav_ueberuns: 'Über eus', nav_faq: 'FAQ', nav_kontakt: 'Kontakt', nav_cta: 'Erschtgspräch abmache',
  hero_eyebrow: 'Vo Dütschland uf Basel',
  hero_title: 'Ihre Wäg i d Schwiiz — klar planet, sicher begleitet.',
  hero_text: 'De Sami Kaune und sis Team begleited Sie bim Wächsel uf Basel und i d Schwiiz — bi de Vorsorg, de Versicherige, de Stüüre und allem, wo bim Uswandere würkli zellt. Persönlich begleitet, mit eme Blick für beidi Site vo de Gränze.',
  hero_cta1: 'Gratis Erschtgspräch', hero_cta2: 'Leischtige aaluege',
  usp1_title: 'Beidi Site vo de Gränze', usp1_text: 'De Sami und sis Team händ beidi Rächts- und Vorsorgsystem im Blick — uf de dütsche wie uf de Schwiizer Site.',
  usp2_title: 'Persönlich begleitet', usp2_text: 'Vom erschte Gspräch bis zur Aamäldig i de Schwiiz — en fixe Aasprächpartner, keis Callcenter.',
  usp3_title: 'Ganzheitlich dänkt', usp3_text: 'Vorsorg, Versicherige, Stüüre und Banking — alles us einere Hand, statt i einzelne Stückli.',
  stats_eyebrow: 'D Schwiiz i Zahle', stats_title: 'Was Sie i de Schwiiz erwartet.',
  stat1_value: "CHF 7'024", stat1_label: 'Medianlohn pro Monet, brutto, Vollziit (2024)',
  stat2_value: 'CHF 694', stat2_label: 'Standardprämie Chrankechasse z Basel-Stadt pro Monet (Erwachseni, Franchise 300, 2026)',
  stat3_value: '27,7 %', stat3_label: 'vo de Bevölkerig ohni Schwiizer Pass (2025) — Sie sind nöd elei',
  stats_source: 'Quelle: Bundesamt für Statistik (Lohnstrukturerhebig 2024, Bevölkerigsstatistik 2025), Gsundheitsdepartement Basel-Stadt / BAG (Prämie 2026)',
  about_eyebrow: 'Über eus', about_title: 'Vo öpperem, wo de Wäg sälber gange isch.',
  about_text: 'How to Schweiz fangt genau det aa, wo klassischi Beratig oft ufhört: a de Gränze. Mir begleited Lüüt, wo de Schritt i d Schwiiz wäged — beruflich oder privat — mit eme Blick für s dütsche und s Schwiizer System und mit eme Netzwerk vo Spezialischte, wänns konkret wird.',
  sami_role: 'Ihre Aasprächpartner z Basel',
  sami_text: 'De Sami hät de Wächsel sälber erläbt: Er isch vo Dütschland i d Schwiiz uusgwanderet und kännt d Hürde nöd us de Theorie, sondern us eigener Erfahrig. Er isch z Basel dihei und Ihri Aalaufstell für d Schwiizer Site: Chrankechasse, Pensionskasse und di praktische Frage rund um de Neuaafang.',
  network_eyebrow: 'Euses Netzwerk', network_title: 'Starchi Partner i de Schwiiz.',
  network_text: 'Für alles, wo über Vorsorg und Versicherig use gaht, schaffed mir mit eme iigspielte Netzwerk i de Schwiiz zäme — drunder Aawält für Frage zum Ufenthalt und zum Arbetsrächt, Stüürberater für d stüürlich Site vo Ihrem Umzug und wiiteri Spezialischte je nach Bedarf. So finded Sie schnäll di richtig Aasprächperson, ohni sälber sueche z müese.',
  network_item1: 'Aawält', network_item2: 'Stüürberater', network_item3: 'Wiiteri Spezialischte',
  leistungen_eyebrow: 'Leischtige', leistungen_title: 'Alles, wo bim Wächsel zellt.',
  more_label: 'Meh erfahre →', back_label: '← Zrugg zur Übersicht', home_label: '← Zrugg zur Startsiite',
  svc1_title: 'Gränzgänger- & Uswanderigsberatig', svc1_text: 'E ehrlichi Standortbestimmig: Wie s Sozialsystem, d Chrankechasse und di drü Süüle vo de Vorsorg zämespieled — und was das konkret für Sie bedüütet.',
  svc2_title: 'Chrankeversicherig Schwiiz', svc2_text: "Anders als in Dütschland wähled Sie Ihri Chrankechasse sälber, unabhängig vom Arbetgeber — Pflicht innert drü Mönet. Mir begleited Sie bi de Grundversicherig, de Franchise (CHF 300–2'500) und de Zuesatzversicherige.",
  svc3_title: 'Altersvorsorg & Renteübertragig', svc3_text: 'Iiordnig vo AHV, Pensionskasse (BVG) — wo Ihre Arbetgeber mindischtens d Hälfti iizahlt — und Süüle 3a, inklusiv Iichaufsmöglichkeite und was mit bestehende dütsche Aasprüch passiert.',
  svc4_title: 'Stüürfrage', svc4_text: 'Orientierig zur Quellestüür, zum Doppelbestüürigsabkomme und zu Ihrer stüürliche Aasässigkeit nach em Umzug.',
  svc5_title: 'Bankverbindig & Vorsorgprodukt', svc5_text: 'Understützig bim Bankkonto und bi de Süüle 3a — stüürlich abzugsfähig und für Dütschi bsunders attraktiv, will s det nüüt Vergliichbars git. Aalaag au i Fonds oder ETFs möglich.',
  svc6_title: 'Absicherig für de Neuaafang', svc6_text: 'D Pensionskasse sichered scho bi Invalidität und im Todesfall ab — mir prüefed, öb das für Sie längt oder öb mer sött ergänze.',
  ablauf_eyebrow: 'Ablauf', ablauf_title: 'So lauft d Zämearbet.',
  step1_title: 'Kännelerne', step1_text: 'Unverbindlichs Erschtgspräch: Mir losed eus Ihri Situation und Ihri Plän in aller Rue aa.',
  step2_title: 'Analyse', step2_text: 'Mir prüefed Ihri aktuelli Vorsorg-, Versicherigs- und Stüürsituation uf beidne Site vo de Gränze.',
  step3_title: 'Konzept', step3_text: 'Sie überchömed es individuells Konzept für Ihre Wächsel — klar und verständlich erklärt.',
  step4_title: 'Umsetzig & Begleitig', step4_text: 'Mir setzed d Massnahme zäme um und bliibed au nach em Umzug Ihre Aasprächpartner.',
  faq_eyebrow: 'Hüüfigi Frage', faq_title: 'Was Uswanderer eus am hüüfigschte fröged.',
  faq_note: 'Stand: 2026. D Antworte gänd en erschte Überblick und ersetzed kei individuelli Beratig.',
  faq: [
    { q: 'Weli Bewilligung bruuch ich als Dütschi oder Dütsche?',
      a: 'Dank em Freizügigkeitsabkomme zwüsche de EU und de Schwiiz isch de Wäg relativ eifach. Mit eme Arbetsvertrag ab eim Jahr oder unbefrischtet überchömed Sie i de Regel d Ufenthaltsbewilligung B, bi chürzere Verträg d Churzufenthaltsbewilligung L. Wer in Dütschland wohne bliibt und mindischtens eimal pro Wuche det hei gaht, überchunnt d Gränzgängerbewilligung G. Nach em Umzug mälded Sie sich innert 14 Täg und vor em Arbetsbeginn bi Ihrer Wohngmeind aa.' },
    { q: 'Bis wänn muess ich mich chrankeversichere?',
      a: 'Innert drü Mönet nach em Zuezug. D Versicherig gilt dänn rückwirkend ab em Tag vo Ihrem Zuezug. Gränzgänger us Dütschland händ es Wahlrächt: Sie chönd sich innert drü Mönet nach em Arbetsbeginn für d Schwiizer Chrankeversicherig oder für e Versicherig in Dütschland entscheide. Die Wahl chamer spöter nur in Uusnahmefäll ändere.' },
    { q: 'Was choscht d Chrankechasse z Basel?',
      a: 'D Standardprämie für Erwachseni z Basel-Stadt liit 2026 bi CHF 694 pro Monet (Franchise CHF 300, mit Unfalldeckig). Mit ere höchere Franchise oder eme Huusarzt- oder Telmed-Modell zahled Sie spürbar weniger. Wer mindischtens 8 Stund pro Wuche aagstellt isch, isch über de Arbetgeber gäge Unfall versicheret und cha d Unfalldeckig i de Chrankechasse uusschlüüsse.' },
    { q: 'Was passiert mit minere dütsche Rente?',
      a: 'Ihri in Dütschland erworbne Aasprüch bliibed bestah. Biitragsziite i beidne Länder werded für d Mindeschtversicherigsziite gägesiitig aagrächnet. Im Rentealter zahlt jedes Land de Teil, wo Sie det erworbe händ — d dütschi Rente cha au i d Schwiiz überwise werde.' },
    { q: 'Wie wird ich i de Schwiiz bestüüret?',
      a: "Mit ere B-Bewilligung wird d Stüür zerscht diräkt vom Lohn abzoge (Quellestüür). Liit Ihre Bruttolohn über CHF 120'000 pro Jahr, folgt automatisch e ordentlichi Stüürerklärig. Drunder chönd Sie die bis zum 31. März vom Folgejahr beaaträge, zum Biispiil zum d Iizahlige i d Süüle 3a abzzieh. Gränzgänger zahled i de Schwiiz höchschtens 4,5 % Quellestüür und werded in Dütschland bestüüret, wobi d Schwiizer Stüür aagrächnet wird." },
    { q: 'Wie vill chan ich i d Süüle 3a iizahle?',
      a: "Aagstellti mit Pensionskasse chönd 2026 bis CHF 7'258 iizahle. Ohni Pensionskasse sinds bis 20 % vom Erwerbsiikomme, höchschtens CHF 36'288. D Iizahlige chönd Sie vom stüürbare Iikomme abzieh." },
    { q: 'Was choscht s Erschtgspräch?',
      a: 'Nüüt. S Erschtgspräch isch gratis und unverbindlich. Mir losed eus Ihri Situation aa und säged Ihne offe, wo mir chönd hälfe.' }
  ],
  kontakt_eyebrow: 'Kontakt', kontakt_title: 'Parat für Ihre Neuaafang?',
  kontakt_text: 'Schriibed Sie eus churz Ihri Situation — mir mälded eus für es unverbindlichs Erschtgspräch bi Ihne.',
  label_name: 'Name', label_email: 'E-Mail', label_phone: 'Telefon (optional)', label_situation: 'Ihri Situation',
  label_consent_before: 'Ich bi iiverstande, dass mini Aagabe für d Bearbeitig vo minere Aafrog bruucht werded. Meh dezue i de ', label_consent_link: 'Dateschutzerklärig', label_consent_after: '.',
  btn_send: 'Nachricht schicke',
  form_invalid: 'Bitte füllet Sie Name, E-Mail und Ihri Situation us und bestätiged Sie d Iiwilligung.',
  form_nomail: 'S Kontaktformular isch no nöd verbunde. Bitte bruuched Sie vorerscht d Kontaktdate.',
  form_ok: 'Ihres E-Mail-Programm wird göffnet …', form_subject: 'Aafrog über How to Schweiz',
  sami_contact_role: 'Aasprächpartner Basel, Schwiiz',
  ph_phone: '[Telefonnummere]', ph_email: '[E-Mail-Adrässe]',
  footer_impressum: 'Impressum', footer_datenschutz: 'Dateschutz', footer_partner: 'Für Berater',
  footer_copyright: '© 2026 How to Schweiz.',
  footer_disclaimer: 'Die Siite ersetzt kei individuelli Rächts- oder Stüürberatig.',
  details: {
    svc1: { intro: 'De Wächsel i d Schwiiz betrifft meh als nur de Wohnort: Sozialversicherig, Stüüre, Chrankeversicherig und Vorsorg folged eigene Regle, wo sich i wichtige Pünkt vo de dütsche underscheided. E früezitigi Standortbestimmig hilft, tüüri Fehler z vermiide.',
      h1: 'Gränzgänger oder Uswanderer?', p1: 'Öb Sie i de Schwiiz schaffed und in Dütschland wohne bliibed (Gränzgänger) oder ganz zügled, macht en grosse Underschiid — bi de Stüüre, de Sozialversicherig und de Chrankechasse gälted jewiils anderi Regle. Mir kläred am Aafang, weli Situation uf Sie zuetrifft.',
      h2: 'Di wichtigschte Baustelle im Überblick', p2: 'Chrankeversicherig (Pflicht innert drü Mönet), di drü Süüle vo de Altersvorsorg, d stüürlich Aasässigkeit und möglichi Doppelbestüürig — alles hanget zäme und sött nöd elei aagluegt werde. Genau det setzt eusi Beratig aa.',
      h3: 'De Wohnort entscheidet mit', p3: 'D Schwiiz hät 26 Kantön mit jewiils eigener Stüürhoheit, und au innerhalb vomene Kanton setzt jedi Gmeind ihre eigene Stüürfuess. Drum chönd scho es paar Kilometer — mängisch sogar e Strass wiiter i de Nachbargmeind oder im Nachbarkanton — en spürbare Underschiid bi de Stüürlascht mache. Mir dänked die Frag früezitig mit, bevor Sie sich für en Wohnort entscheided.' },
    svc2: { intro: 'Innert drü Mönet nach em Zuezug müend Sie sich bi ere Schwiizer Chrankechasse versichere — anders als in Dütschland wähled Sie die ganz frei, unabhängig vom Arbetgeber.',
      h1: 'Grundversicherig (KVG): gsetzlich gliich, im Service andersch', p1: "D Leischtige vo de obligatorische Grundversicherig sind bi jedere Chrankechasse gliich — Ärzt, Spitalufenthalt und Medikamänt sind abdeckt. Underschiid gits vor allem bi de Prämie, bim Service und bi de Wahl vo de Franchise, wo zwüsche CHF 300 und CHF 2'500 pro Jahr liit: Je höcher d Franchise, desto tüüfer d monatlich Prämie.",
      h2: 'Zuesatzversicherig: sinnvoll ergänze', p2: 'Freiwilligi Zuesatzversicherige decked zum Biispiil di halbprivat oder privat Spitalabteilig, d Chefarztbehandlig, alternativi Heilmethode oder Biiträg as Fitness-Abo ab. Mir lueged zäme, was für Ihri Situation Sinn macht — und was nöd.' },
    svc3: { intro: 'D Schwiizer Altersvorsorg staht uf drü Süüle, wo zäme de Läbesstandard im Alter und bi Invalidität oder im Todesfall sichere sölled.',
      h1: 'Di drü Süüle', p1: '1. Süüle (AHV): di staatlich Grundabsicherig, obligatorisch für alli. 2. Süüle (Pensionskasse/BVG): di beruflich Vorsorg über de Arbetgeber, wo mindischtens d Hälfti vo de Biiträg übernimmt. 3. Süüle: di freiwillig, privat Ergänzig — d Süüle 3a isch debi stüürlich abzugsfähig und hät in Dütschland kei diräkti Entsprächig.',
      h2: 'Was mit de dütsche Aasprüch passiert', p2: 'Bestehendi dütschi Renteaasprüch gönd bim Wächsel nöd verlore, folged aber eigene Regle — s Freizügigkeitsabkomme zwüsche de EU und de Schwiiz koordiniert beidi System. Bim Wächsel vo de Pensionskasse lohnt sich zuedem en Blick uf de Deckigsgrad und möglichi Iichäuf. Di gnaue Uswürkige bespräched mir aahand vo Ihrer persönliche Situation.' },
    svc4: { intro: 'Mit em Wächsel i d Schwiiz ändered sich au Ihri stüürlich Situation — vor allem im Umzugsjahr lohnt sich en gnaue Blick, damit kei Doppelbestüürig entstaht.',
      h1: 'Quellestüür und Doppelbestüürigsabkomme', p1: 'Vill Zuezogeni werded i de Schwiiz zerscht diräkt a de Quelle bestüüret. S Doppelbestüürigsabkomme zwüsche Dütschland und de Schwiiz regled, welem Land i wele Fäll s Bestüürigsrächt zuestaht, damit s Iikomme nöd doppelt versteuret wird.',
      h2: 'Stüürlichi Aasässigkeit', p2: 'Wo Sie stüürlich aasässig sind, hanget vom Wohnsitz und vom Läbesmittelpunkt ab — grad im Übergangsjahr isch das nöd immer klar. Mir ordned Ihri individuelli Situation ii und verwiised bi Bedarf a spezialisierti Stüürberatig.' },
    svc5: { intro: 'Es Schwiizer Bankkonto und di richtig Vorsorglösig ghöred zu de erschte praktische Schritt nach em Zuezug.',
      h1: 'Süüle 3a: stüürlich abzugsfähig', p1: "Iizahlige i d Süüle 3a chönd vom stüürbare Iikomme abzoge werde — 2026 bis CHF 7'258 für Aagstellti mit Pensionskasse. So en Vorteil gits in Dütschland nöd. Je nach Lösig wird s Kapital verzinst oder i Fonds oder ETFs aagleit, zum langfrischtig Vermöge ufzbaue.",
      h2: 'Bankkonto und bestehendi Verträg', p2: 'Mir understützed Sie bi de Kontoeröffnig und lueged, weli bestehende dütsche Verträg — zum Biispiil Läbesversicherige oder Sparplän — sinnvoll wiitergführt oder aapasst werde sötted.' },
    svc6: { intro: 'En Neuaafang i de Schwiiz isch au en guete Moment, zum di eigeti Absicherig z überprüefe.',
      h1: 'Was d Pensionskasse scho abdeckt', p1: 'D 2. Süüle schützt nöd nur im Alter, sondern au bi Invalidität und im Todesfall — bi Erwerbsunfähigkeit oder für Hinterbliebeni chönd Leischtige uuszahlt werde. Wie höch die sind, hanget vom jewiilige Vorsorgplan ab.',
      h2: 'Wo sich e Ergänzig cha lohne', p2: 'Öb di iibaut Absicherig für Ihri Familiesituation längt oder öb e privati Ergänzig Sinn macht, prüefed mir zäme — gnau wie d Frag, öb bestehendi dütschi Police nach em Umzug no passed.' }
  }
};
